ignore:
  - vulnerability: CVE-2022-3996
    package:
      name: libssl3
      version: 3.0.7-r0

  - vulnerability: CVE-2022-3996
    package:
      name: libcrypto3
      version: 3.0.7-r0

  - vulnerability: CVE-2023-5363
    package:
      name: libssl3
      version: 3.1.3-r0

  - vulnerability: CVE-2023-5363
    package:
      name: libcrypto3
      version: 3.1.3-r0

  - vulnerability: CVE-2023-45853
    package:
      name: zlib
      version: 1.3.1-r2
